[package]
name = "barexp-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
once_cell = "1.20.2"
syn = { version = "2.0.90", features = ["extra-traits", "full"] }
quote = "1.0.37"
proc-macro2 = "1.0.92"
